name: Test activity checker tool

on:
  workflow_dispatch:

jobs:
  test_activity_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: x64
      - name: clean install maven
        run: mvn clean install
      - name: Run tests
        run: mvn test